/*
Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

function main() {
	let prev = 1;
	let curr = 2;
	let aux = prev;
	let sum = 0;

	while (curr < 4000000) {
		sum += curr % 2 === 0 ? curr : 0;

		aux = prev;
		prev = curr;
		curr = aux + prev;
	}

	console.log(sum);
	return sum;
}

main();